<table>
  <thead>
    <tr>
      <th><b>SEMESTER</b></th>
      <th><b>NIS</b></th>
      <th><b>NAMA</b></th>
      <th><b>KELAS</b></th>
      <th><b>MAPEL</b></th>
      <th><b>NILAI</b></th>
      <th><b>KETERANGAN</b></th>
    </tr>
  </thead>
</table>